(()=>{
 'use strict';const q=s=>document.querySelector(s),core=CASEBOARD_CORE,view=q('#boardViewport'),world=q('#boardWorld'),svg=q('#boardThreads'),nodes=q('#boardNodes'),seals=q('#boardSeals');let board=core.initial(),ready=false,editing=false,connecting=false,source=null,selection=null,drag=null,draft=null,edgeDraft=null,zoom=1,tx=0,ty=0,initialized=false,suppressClick=false;let zoneDraft=null;const zoneEls=new Map();const nodeEls=new Map(),edgeEls=new Map(),demo=new URLSearchParams(location.search).has('showcase');
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};

 function hint(text){q('#boardHint').textContent=text||(connecting?(source?'选择另一个人物或档案完成连线 · Esc 取消':'依次选择两个档案建立连线 · Esc 取消'):editing?'编辑中 · 拖动卡片 / 结界标题 · 拉动结界四角调整范围':'拖动画面查看 · 滚轮缩放 · 点击卡片或封签阅读')}
 function save(){if(!ready)return;core.validate(board);if(!demo)document.dispatchEvent(new CustomEvent('board:change',{detail:core.copy(board)}));}

 function camera(){world.style.setProperty('--ward-control-scale',Math.min(2.5,1/zoom));world.style.transform=`translate(${tx}px,${ty}px) scale(${zoom})`;const x=-tx/zoom,y=-ty/zoom,w=view.clientWidth/zoom,h=view.clientHeight/zoom;Object.assign(svg.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});svg.setAttribute('viewBox',`${x} ${y} ${w} ${h}`);view.style.backgroundPosition=`${tx}px ${ty}px`;view.style.backgroundSize=`${80*zoom}px ${80*zoom}px`;}
 function fit(){cancelDrag();const boxes=board.nodes.map(n=>{const e=nodeEls.get(n.id),w=e?.offsetWidth||156,h=e?.offsetHeight||234;return {x:n.x-w/2,y:n.y-h/2,width:w,height:h}});if(!boxes.length)boxes.push(...board.zones);const left=boxes.length?Math.min(...boxes.map(b=>b.x))-80:-400,top=boxes.length?Math.min(...boxes.map(b=>b.y))-80:-300,right=boxes.length?Math.max(...boxes.map(b=>b.x+b.width))+80:400,bottom=boxes.length?Math.max(...boxes.map(b=>b.y+b.height))+80:300;zoom=Math.min(1,view.clientWidth/Math.max(1,right-left),view.clientHeight/Math.max(1,bottom-top))||1;tx=view.clientWidth/2-(left+right)/2*zoom;ty=view.clientHeight/2-(top+bottom)/2*zoom;q('#boardRegion').value='';camera();}
 function changeZoom(f,cx=view.clientWidth/2,cy=view.clientHeight/2){const next=Math.min(2,Math.max(Math.min(.01,zoom/10),zoom*f));tx=cx-(cx-tx)*next/zoom;ty=cy-(cy-ty)*next/zoom;zoom=next;camera()}
 function renderRegions(){const picker=q('#boardRegion'),previous=picker.value;picker.replaceChildren(el('option','定位区域…'));picker.firstChild.value='';for(const z of board.zones){const option=el('option',z.name);option.value=z.id;picker.append(option)}picker.value=previous;}
 function portraitImage(n,detail=false){const crop=window.CASEBOARD_PORTRAITS?.[n.id];if(crop&&n.portrait===crop.path){const drawing=document.createElementNS('http://www.w3.org/2000/svg','svg'),image=document.createElementNS(drawing.namespaceURI,'image');drawing.setAttribute('viewBox',`${crop.x} ${crop.y} ${crop.size} ${crop.size}`);drawing.setAttribute('class','source-portrait');drawing.setAttribute('role','img');drawing.setAttribute('aria-label',detail?n.name:'');if(!detail)drawing.setAttribute('aria-hidden','true');image.setAttribute('href',crop.path);image.setAttribute('width',crop.width);image.setAttribute('height',crop.height);drawing.append(image);return drawing}const img=el('img');img.src=n.portrait;img.alt=detail?n.name:'';img.draggable=false;img.loading='lazy';return img;}
 q('#boardRegion').onchange=()=>{const z=board.zones.find(z=>z.id===q('#boardRegion').value);if(!z)return;cancelDrag();zoom=Math.min(1.5,Math.min(view.clientWidth/(z.width+80),view.clientHeight/(z.height+80))*.94);tx=view.clientWidth/2-(z.x+z.width/2)*zoom;ty=view.clientHeight/2-(z.y+z.height/2)*zoom;selection=null;q('#boardDetails').hidden=true;geometry();camera();};
 function geometry(){zoneGeometry();for(const n of board.nodes){const e=nodeEls.get(n.id);if(e){e.style.left=n.x+'px';e.style.top=n.y+'px';e.classList.toggle('selected',selection?.kind==='node'&&selection.id===n.id);e.classList.toggle('connect-source',source===n.id)}}for(const e of board.edges){const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to),els=edgeEls.get(e.id);if(!a||!b||!els)continue;const bend=Math.min(70,Math.hypot(a.x-b.x,a.y-b.y)*.08),mx=(a.x+b.x)/2,my=(a.y+b.y)/2+bend;els.path.setAttribute('d',`M${a.x},${a.y} Q${mx},${my} ${b.x},${b.y}`);els.seal.style.left=mx+'px';els.seal.style.top=((a.y+b.y)/2+bend/2)+'px';const selected=selection?.kind==='edge'&&selection.id===e.id;els.path.classList.toggle('selected',selected);els.seal.classList.toggle('selected',selected)}}
 function portrait(n){const box=el('span',undefined,'node-portrait'),fallback=()=>{box.replaceChildren(el('span',n.name.slice(0,1),'empty-portrait'),el('span',n.kind==='place'?'地貌待绘':'肖像待绘','portrait-caption'))};if(n.portrait){const img=portraitImage(n);img.onerror=fallback;box.append(img)}else fallback();return box}
 function render(){renderRegions();renderZones();nodes.replaceChildren();seals.replaceChildren();svg.replaceChildren();nodeEls.clear();edgeEls.clear();for(const e of board.edges){const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','case-thread');applyEdgeStyle(path,e.style);svg.append(path);const seal=el('button',e.note||'添加备注','case-seal');seal.style.setProperty('--thread-color',core.style(e.style,'edge').color);seal.type='button';seal.setAttribute('aria-label',a.name+'与'+b.name+'的连线');seal.title=e.note||'尚无连线备注';seal.dataset.id=e.id;seal.onclick=()=>{if(suppressClick)return;select('edge',e.id)};seals.append(seal);edgeEls.set(e.id,{path,seal})}for(const n of board.nodes){const b=el('button',undefined,'case-node');b.type='button';b.dataset.id=n.id;b.dataset.kind=n.kind;b.dataset.status=n.status;applyNodeStyle(b,n.style);b.setAttribute('aria-label',n.name);b.append(el('span',({person:'人物',place:'地点',group:'组织'}[n.kind]),'node-kind'));if(n.kind!=='group')b.append(portrait(n));b.append(el('strong',n.name));if(n.kind==='person'){const p=core.personPreview(n);b.append(el('small',p.role||'职业：？','node-role'),el('small','等级 '+(p.level??'？')+(p.status?'（'+p.status+'）':''),'node-level'))}else{b.append(el('small',n.role||'线索档案'));if(n.status)b.append(el('small',n.status))}b.onclick=()=>{if(suppressClick){suppressClick=false;return}if(connecting){if(!source){source=n.id;geometry();hint();return}if(source===n.id){hint('请选择另一个档案');return}const existing=board.edges.find(e=>[e.from,e.to].includes(source)&&[e.from,e.to].includes(n.id));openEdge(existing||{id:crypto.randomUUID(),from:source,to:n.id,note:''});source=null;connecting=false;syncMode();return}select('node',n.id)};b.addEventListener('keydown',e=>{if(!editing||connecting||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();n.x=n.x+(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0);n.y=n.y+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0);geometry();save()});nodes.append(b);nodeEls.set(n.id,b)}geometry();details()}

 function zoneGeometry(){for(const z of board.zones){const box=zoneEls.get(z.id);if(!box)continue;Object.assign(box.style,{left:z.x+'px',top:z.y+'px',width:z.width+'px',height:z.height+'px'});box.classList.toggle('selected',selection?.kind==='zone'&&selection.id===z.id)}}
 function renderZones(){q('#boardZones').replaceChildren();zoneEls.clear();for(const z of board.zones){const box=el('div',undefined,'case-ward');box.dataset.zone=z.id;box.dataset.tone=z.tone;box.setAttribute('role','group');box.setAttribute('aria-label',z.name+'结界');const title=el('button',z.name,'ward-title');title.type='button';title.setAttribute('aria-label','结界：'+z.name);title.onclick=()=>{if(suppressClick){suppressClick=false;return}if(!connecting)select('zone',z.id)};box.append(title);for(const corner of ['nw','ne','sw','se']){const h=el('button',undefined,'ward-handle');h.type='button';h.dataset.corner=corner;h.setAttribute('aria-label',z.name+'：调整'+({nw:'左上',ne:'右上',sw:'左下',se:'右下'}[corner])+'范围');h.onclick=()=>{if(!suppressClick&&editing)select('zone',z.id)};box.append(h)}box.addEventListener('keydown',e=>{if(!editing||connecting||!e.key.startsWith('Arrow'))return;e.preventDefault();e.stopPropagation();const dx=e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0,dy=e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0;const corner=e.target.dataset.corner;const old=core.copy(z);drag={z,old,corner};moveZoneDrag(dx,dy);drag=null;zoneGeometry();save();details()});q('#boardZones').append(box);zoneEls.set(z.id,box)}}
 function zoneDetails(){q('#boardStyle').hidden=true;const z=board.zones.find(z=>z.id===selection.id);q('#boardDetails').hidden=!z;if(!z)return;q('#boardModify').hidden=q('#boardRemove').hidden=!editing;q('#boardModify').textContent='编辑结界';q('#boardDetailKind').textContent='结界分组';q('#boardDetailTitle').textContent=z.name;const contained=board.nodes.filter(n=>n.x>=z.x&&n.x<=z.x+z.width&&n.y>=z.y&&n.y<=z.y+z.height);q('#boardDetailBody').replaceChildren(el('p','范围内的档案 · '+contained.length),el('p',contained.map(n=>n.name).join('、')||'暂无档案'),el('p',editing?'拖动标题移动结界，拖动四角调整范围；也可点击编辑结界输入尺寸。':'开启编辑模式后可调整结界。'),el('p','结界依据卡片中心划分，可重叠。移动结界不会移动档案或改变已有连线。'))}
 function openZone(z){zoneDraft=z?core.copy(z):{id:crypto.randomUUID(),name:'',tone:'sage',x:(view.clientWidth/2-tx)/zoom-240,y:(view.clientHeight/2-ty)/zoom-180,width:480,height:360};for(const k of ['name','tone','x','y','width','height'])q('#boardZone'+k[0].toUpperCase()+k.slice(1)).value=zoneDraft[k];q('#boardZoneError').textContent='';q('#boardZoneDialog').showModal();q('#boardZoneName').focus()}
 q('#boardNewZone').onclick=()=>{connecting=false;source=null;syncMode();openZone()};q('#boardZoneCancel').onclick=()=>q('#boardZoneDialog').close();q('#boardZoneDialog').addEventListener('close',()=>zoneDraft=null);
 q('#boardZoneForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!zoneDraft)return;try{const z={...zoneDraft};for(const k of ['name','tone','x','y','width','height']){const v=q('#boardZone'+k[0].toUpperCase()+k.slice(1)).value;z[k]=['name','tone'].includes(k)?v.trim():Number(v)}const next=core.copy(board),i=next.zones.findIndex(x=>x.id===z.id);if(i<0)next.zones.push(z);else next.zones[i]=z;board=core.validate(next);selection={kind:'zone',id:z.id};q('#boardZoneDialog').close();render();save()}catch(err){q('#boardZoneError').textContent=err.message}};
 function startZoneDrag(e){if(!editing||connecting)return;const box=e.target.closest('.case-ward'),z=board.zones.find(z=>z.id===box.dataset.zone);suppressClick=false;drag={id:e.pointerId,sx:e.clientX,sy:e.clientY,z,old:core.copy(z),corner:e.target.dataset.corner,moved:false};view.setPointerCapture(e.pointerId)}
 function moveZoneDrag(dx,dy){const {z,old:o,corner:c}=drag;if(!c){z.x=o.x+dx;z.y=o.y+dy}else{let l=o.x,t=o.y,r=o.x+o.width,b=o.y+o.height;if(c.includes('w'))l=Math.min(r-240,l+dx);else r=Math.max(l+240,r+dx);if(c.includes('n'))t=Math.min(b-200,t+dy);else b=Math.max(t+200,b+dy);Object.assign(z,{x:l,y:t,width:r-l,height:b-t})}zoneGeometry()}
 function select(kind,id){selection={kind,id};geometry();details()}
 function details(){if(selection?.kind==='zone'){zoneDetails();return}const d=q('#boardDetails'),body=q('#boardDetailBody'),item=selection?.kind==='node'?board.nodes.find(n=>n.id===selection.id):board.edges.find(e=>e.id===selection?.id);d.hidden=!item;q('#boardStyle').hidden=!editing||!item;if(!item)return;q('#boardModify').hidden=q('#boardRemove').hidden=!editing;q('#boardDetailKind').textContent=selection.kind==='node'?({person:'人物档案',place:'地点档案',group:'组织档案'}[item.kind]):'连线封签';q('#boardDetailTitle').textContent=selection.kind==='node'?item.name:board.nodes.find(n=>n.id===item.from).name+' ↔ '+board.nodes.find(n=>n.id===item.to).name;body.replaceChildren();function field(title,value){body.append(el('h3',title),el('p',value||'尚未记录'))}if(selection.kind==='edge'){field('连线备注',item.note);q('#boardModify').textContent='编辑备注'}else{q('#boardModify').textContent='编辑资料';if(item.portrait){const img=portraitImage(item,true);body.append(img)}else body.append(el('p',item.kind==='place'?'地貌待绘 · 可在工作台补全':'肖像待绘 · 可在工作台补全'));if(item.kind==='person'){const p=core.personPreview(item);field('职业',p.role||'？');field('等级',String(p.level??'？'));field('种族',item.race);if(p.status)field('特殊状态',p.status)}else field('身份',[item.race,item.role,item.status].filter(Boolean).join(' · '));field('档案备注',item.notes);if(item.appearance)field('肖像描述',item.appearance)}if(!editing)body.append(el('p','开启编辑模式后可修改。'))}
 function syncMode(){q('#boardEdit').setAttribute('aria-pressed',String(editing));q('#boardEdit').textContent=editing?'完成编辑':'编辑模式';q('#boardNew').hidden=q('#boardNewZone').hidden=q('#boardConnect').hidden=!editing;world.classList.toggle('editing',editing);q('#boardConnect').setAttribute('aria-pressed',String(connecting));world.classList.toggle('connecting',connecting);geometry();details();hint()}
 q('#boardEdit').onclick=()=>{if(!ready)return;cancelDrag();editing=!editing;connecting=false;source=null;syncMode()};q('#boardConnect').onclick=()=>{connecting=!connecting;source=null;selection=null;q('#boardDetails').hidden=true;syncMode()};q('#boardCloseDetails').onclick=()=>{selection=null;q('#boardDetails').hidden=true;geometry()};

 let styleDraft=null;
 function readStyleFields(){return Object.fromEntries([...q('#boardStyleFields').querySelectorAll('[data-style-field]')].map(input=>[input.dataset.styleField,input.type==='number'?Number(input.value):input.value]));}
 function stylePreview(){
  if(!styleDraft)return;try{
   const style=core.style(readStyleFields(),styleDraft.kind),preview=q('#boardStylePreview');preview.replaceChildren();
   if(styleDraft.kind==='node'){const card=el('div',undefined,'case-node style-card');card.dataset.kind='person';applyNodeStyle(card,style);card.append(el('span','档案','node-kind'),el('strong','样式预览'),el('small','人物、地点和组织均可使用'));preview.append(card)}
   else{const drawing=document.createElementNS('http://www.w3.org/2000/svg','svg'),line=document.createElementNS(drawing.namespaceURI,'path');drawing.setAttribute('viewBox','0 0 360 70');line.setAttribute('d','M15 45 Q180 5 345 45');line.setAttribute('class','case-thread');applyEdgeStyle(line,style);drawing.append(line);preview.append(drawing)}
   q('#boardStyleError').textContent='';
  }catch(err){q('#boardStyleError').textContent=err.message}
 }
 function fillStyleFields(value){q('#boardStyleFields').querySelectorAll('[data-style-field]').forEach(input=>input.value=value[input.dataset.styleField]);stylePreview();}
 q('#boardStyle').onclick=()=>{
  if(!editing||!selection||selection.kind==='zone')return;
  const item=(selection.kind==='node'?board.nodes:board.edges).find(x=>x.id===selection.id);if(!item)return;
  styleDraft={kind:selection.kind,id:item.id};q('#boardStyleHeading').textContent=selection.kind==='node'?'档案样式':'连线样式';
  const specs=selection.kind==='node'?[['color','卡片颜色','color'],['border','边框颜色','color'],['text','文字颜色','color'],['shape','外框形状','select',[['arched','拱形'],['square','方形'],['rounded','圆角']]]]:[['color','连线颜色','color'],['width','线条粗细','number'],['pattern','线条样式','select',[['solid','实线'],['dashed','虚线'],['dotted','点线']]]];
  const fields=q('#boardStyleFields');fields.replaceChildren();for(const [key,title,type,options] of specs){const label=el('label',title),input=el(type==='select'?'select':'input');input.dataset.styleField=key;input.id='boardStyle-'+key;if(type==='select'){for(const [value,name] of options){const opt=el('option',name);opt.value=value;input.append(opt)}}else{input.type=type;if(type==='number'){input.min=1;input.max=8;input.step=1;input.required=true}}
   label.append(input);fields.append(label);input.addEventListener('input',stylePreview);input.addEventListener('change',stylePreview);
  }
  fillStyleFields(core.style(item.style,selection.kind));q('#boardStyleDialog').showModal();fields.querySelector('input').focus();
 };
 q('#boardStyleReset').onclick=()=>{if(styleDraft)fillStyleFields(core.defaults[styleDraft.kind]);};
 document.querySelectorAll('[data-close-style]').forEach(b=>b.onclick=()=>q('#boardStyleDialog').close());
 q('#boardStyleDialog').addEventListener('close',()=>styleDraft=null);
 q('#boardStyleForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!styleDraft)return;try{const next=core.copy(board),item=(styleDraft.kind==='node'?next.nodes:next.edges).find(x=>x.id===styleDraft.id);if(!item)throw Error('这份记录已不存在');item.style=core.style(readStyleFields(),styleDraft.kind);board=core.validate(next);q('#boardStyleDialog').close();render();save()}catch(err){q('#boardStyleError').textContent=err.message}};

 function personKindChanged(){q('#boardLevelField').hidden=q('#boardKind').value!=='person'}q('#boardKind').onchange=personKindChanged;
 function openPerson(n){draft=n?core.copy(n):{id:crypto.randomUUID(),kind:'person',name:'',race:'',role:'',status:'',notes:'',appearance:'',portrait:'',x:(view.clientWidth/2-tx)/zoom,y:(view.clientHeight/2-ty)/zoom};q('#boardPersonHeading').textContent=n?'编辑档案':'新建人物';q('#boardKind').value=draft.kind;for(const [field,id] of Object.entries({name:'Name',race:'Race',role:'Role',status:'Status',notes:'Notes',appearance:'Appearance',portrait:'Portrait'}))q('#board'+id).value=draft[field];const preview=core.personPreview(draft);q('#boardLevel').value=String(preview.level??'?');if(draft.kind==='person')q('#boardRole').value=preview.role;personKindChanged();q('#boardPersonError').textContent='';q('#boardPersonDialog').showModal();q('#boardName').focus()}
 q('#boardNew').onclick=()=>openPerson();document.querySelectorAll('[data-close-person]').forEach(b=>b.onclick=()=>q('#boardPersonDialog').close());q('#boardPersonDialog').addEventListener('close',()=>draft=null);
 q('#boardPersonForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!draft)return;try{const n={...draft,kind:q('#boardKind').value};for(const [field,id] of Object.entries({name:'Name',race:'Race',role:'Role',status:'Status',notes:'Notes',appearance:'Appearance',portrait:'Portrait'}))n[field]=q('#board'+id).value.trim();if(n.kind==='person')n.level=q('#boardLevel').value==='?'?null:Number(q('#boardLevel').value);const next=core.copy(board),i=next.nodes.findIndex(x=>x.id===n.id);if(i<0)next.nodes.push(n);else next.nodes[i]=n;board=core.validate(next);selection={kind:'node',id:n.id};q('#boardPersonDialog').close();render();save()}catch(err){q('#boardPersonError').textContent=err.message}};
 function openEdge(e){edgeDraft=core.copy(e);q('#boardEdgeNames').textContent=board.nodes.find(n=>n.id===e.from).name+' ↔ '+board.nodes.find(n=>n.id===e.to).name;q('#boardEdgeNote').value=e.note;q('#boardEdgeDialog').showModal();q('#boardEdgeNote').focus()}
 q('#boardCancelEdge').onclick=()=>q('#boardEdgeDialog').close();q('#boardEdgeDialog').addEventListener('close',()=>edgeDraft=null);q('#boardEdgeForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!edgeDraft)return;const next=core.copy(board),edge={...edgeDraft,note:q('#boardEdgeNote').value.trim()},i=next.edges.findIndex(x=>x.id===edge.id);if(i<0)next.edges.push(edge);else next.edges[i]=edge;try{board=core.validate(next);selection={kind:'edge',id:edge.id};q('#boardEdgeDialog').close();render();save()}catch(err){hint(err.message)}};
 q('#boardModify').onclick=()=>{if(!editing||!selection)return;if(selection.kind==='zone'){openZone(board.zones.find(z=>z.id===selection.id));return}if(selection.kind==='node')openPerson(board.nodes.find(n=>n.id===selection.id));else openEdge(board.edges.find(e=>e.id===selection.id))};q('#boardRemove').onclick=()=>{if(!editing||!selection)return;q('#boardDeleteText').textContent=selection.kind==='zone'?'只移除结界，所有档案与连线仍然保留。':selection.kind==='node'?'这份档案及其连线将从案件板移除。':'只移除这条连线，人物档案保留。';q('#boardDeleteDialog').showModal()};q('#boardKeep').onclick=()=>q('#boardDeleteDialog').close();q('#boardConfirmDelete').onclick=()=>{if(!editing||!selection)return;const {kind,id}=selection;if(kind==='zone')board.zones=board.zones.filter(z=>z.id!==id);else board.edges=board.edges.filter(e=>kind==='edge'?e.id!==id:e.from!==id&&e.to!==id);if(kind==='node')board.nodes=board.nodes.filter(n=>n.id!==id);selection=null;q('#boardDeleteDialog').close();render();save()};
 view.addEventListener('dragstart',e=>e.preventDefault());view.addEventListener('selectstart',e=>e.preventDefault());view.addEventListener('drop',e=>e.preventDefault());
 view.addEventListener('pointerdown',e=>{if(!ready||e.button!==0)return;e.preventDefault();const clicked=e.target.closest('button');(clicked||view).focus({preventScroll:true});if(editing&&!connecting&&e.target.closest('.ward-title,.ward-handle')){startZoneDrag(e);return}const card=e.target.closest('.case-node'),seal=e.target.closest('.case-seal'),zone=e.target.closest('.case-ward');if(card&&connecting)return;suppressClick=false;const n=card&&editing?board.nodes.find(n=>n.id===card.dataset.id):null;const hit=card?{kind:'node',id:card.dataset.id}:seal?{kind:'edge',id:seal.dataset.id}:e.target.closest('.ward-title')?{kind:'zone',id:zone.dataset.zone}:null;drag={id:e.pointerId,sx:e.clientX,sy:e.clientY,tx,ty,n,hit,oldX:n?.x,oldY:n?.y,moved:false};view.setPointerCapture(e.pointerId);if(n)card.classList.add('dragging')});
 view.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;if(!drag.moved&&Math.hypot(dx,dy)<5)return;drag.moved=true;if(drag.z){moveZoneDrag(dx/zoom,dy/zoom);return}if(drag.n){drag.n.x=drag.oldX+dx/zoom;drag.n.y=drag.oldY+dy/zoom;geometry()}else{tx=drag.tx+dx;ty=drag.ty+dy;camera()}});
 function finishDrag(e,cancel=false){if(!drag||e&&e.pointerId!==drag.id)return;const d=drag;drag=null;if(view.hasPointerCapture(d.id))view.releasePointerCapture(d.id);if(d.z){if(cancel){Object.assign(d.z,d.old);zoneGeometry()}else if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0);save();details()}else select('zone',d.z.id);return}if(d.n){nodeEls.get(d.n.id)?.classList.remove('dragging');if(cancel){d.n.x=d.oldX;d.n.y=d.oldY;geometry()}else if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0);save()}else if(!connecting)select('node',d.n.id)}else if(cancel){tx=d.tx;ty=d.ty;camera()}else if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0)}else if(d.hit)select(d.hit.kind,d.hit.id)}
 function cancelDrag(){finishDrag(null,true)}view.addEventListener('pointerup',e=>finishDrag(e));view.addEventListener('pointercancel',e=>finishDrag(e,true));view.addEventListener('lostpointercapture',e=>finishDrag(e,true));view.addEventListener('wheel',e=>{e.preventDefault();if(drag)return;const r=view.getBoundingClientRect();changeZoom(e.deltaY<0?1.12:1/1.12,e.clientX-r.left,e.clientY-r.top)},{passive:false});
 q('#boardPlus').onclick=()=>changeZoom(1.2);q('#boardMinus').onclick=()=>changeZoom(1/1.2);q('#boardFit').onclick=fit;view.addEventListener('keydown',e=>{if(e.target!==view||!e.key.startsWith('Arrow'))return;e.preventDefault();tx+=e.key==='ArrowRight'?-80:e.key==='ArrowLeft'?80:0;ty+=e.key==='ArrowDown'?-80:e.key==='ArrowUp'?80:0;camera()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelDrag();connecting=false;source=null;syncMode()}});
 let vw=0,vh=0;function resized(){const w=view.clientWidth,h=view.clientHeight;if(initialized){tx+=(w-vw)/2;ty+=(h-vh)/2;camera()}vw=w;vh=h}window.addEventListener('resize',()=>{cancelDrag();resized()});if(window.ResizeObserver)new ResizeObserver(resized).observe(view);
 q('#boardFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{hint('当前浏览器不支持全屏，案件板已铺满窗口。')}};document.addEventListener('fullscreenchange',()=>{const active=!!document.fullscreenElement;q('#boardFullscreen').textContent=active?'退出全屏':'全屏';q('#boardFullscreen').setAttribute('aria-pressed',String(active))});
 window.CaseboardAPI={read:()=>{const s=core.copy(board);if(drag?.n){const n=s.nodes.find(n=>n.id===drag.n.id);n.x=drag.oldX;n.y=drag.oldY}if(drag?.z){Object.assign(s.zones.find(z=>z.id===drag.z.id),drag.old)}return s},apply:s=>{board=core.validate(s);if(selection&&!(selection.kind==='node'?board.nodes:selection.kind==='zone'?board.zones:board.edges).some(x=>x.id===selection.id))selection=null;render()},canApply:()=>!drag&&!connecting&&!document.querySelector('dialog[open]:not(#adventureSaveDialog)'),ready:()=>{ready=true;view.inert=false;q('#boardEdit').disabled=false;if(!initialized){initialized=true;vw=view.clientWidth;vh=view.clientHeight;fit()}hint()}};
 render();if(demo){CaseboardAPI.ready();q('[data-archive-status]').textContent='演示 · 不写入存档'}
})();
