(()=>{
 'use strict';const q=s=>document.querySelector(s),core=CASEBOARD_CORE,view=q('#boardViewport'),world=q('#boardWorld'),svg=q('#boardThreads'),nodes=q('#boardNodes'),seals=q('#boardSeals');let board=core.initial(),ready=false,editing=false,connecting=false,source=null,selection=null,drag=null,draft=null,edgeDraft=null,zoom=1,tx=0,ty=0,initialized=false,suppressClick=false;const nodeEls=new Map(),edgeEls=new Map(),demo=new URLSearchParams(location.search).has('showcase');
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
 function hint(text){q('#boardHint').textContent=text||(connecting?(source?'选择另一个人物或档案完成连线 · Esc 取消':'依次选择两个档案建立连线 · Esc 取消'):editing?'编辑中 · 拖动卡片摆放 · 点击卡片或封签编辑 · 方向键可微调卡片':'拖动空白处查看 · 滚轮缩放 · 点击卡片或封签阅读')}
 function save(){if(!ready)return;core.validate(board);if(!demo)document.dispatchEvent(new CustomEvent('board:change',{detail:core.copy(board)}));}
 function bounds(){tx=Math.min(view.clientWidth*.65,Math.max(view.clientWidth*.35-1800*zoom,tx));ty=Math.min(view.clientHeight*.65,Math.max(view.clientHeight*.35-1200*zoom,ty))}
 function camera(){bounds();world.style.transform=`translate(${tx}px,${ty}px) scale(${zoom})`}
 function fit(){zoom=Math.min(1,Math.max(.18,Math.min(view.clientWidth/1800,view.clientHeight/1200)*.94));tx=(view.clientWidth-1800*zoom)/2;ty=(view.clientHeight-1200*zoom)/2;camera()}
 function changeZoom(f,cx=view.clientWidth/2,cy=view.clientHeight/2){const next=Math.min(2,Math.max(.18,zoom*f));tx=cx-(cx-tx)*next/zoom;ty=cy-(cy-ty)*next/zoom;zoom=next;camera()}
 function geometry(){for(const n of board.nodes){const e=nodeEls.get(n.id);if(e){e.style.left=n.x+'px';e.style.top=n.y+'px';e.classList.toggle('selected',selection?.kind==='node'&&selection.id===n.id);e.classList.toggle('connect-source',source===n.id)}}for(const e of board.edges){const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to),els=edgeEls.get(e.id);if(!a||!b||!els)continue;const bend=Math.min(70,Math.hypot(a.x-b.x,a.y-b.y)*.08),mx=(a.x+b.x)/2,my=(a.y+b.y)/2+bend;els.path.setAttribute('d',`M${a.x},${a.y} Q${mx},${my} ${b.x},${b.y}`);els.seal.style.left=mx+'px';els.seal.style.top=((a.y+b.y)/2+bend/2)+'px';const selected=selection?.kind==='edge'&&selection.id===e.id;els.path.classList.toggle('selected',selected);els.seal.classList.toggle('selected',selected)}}
 function portrait(n){const box=el('span',undefined,'node-portrait'),fallback=()=>{box.replaceChildren(el('span',n.name.slice(0,1),'empty-portrait'),el('span','肖像待绘','portrait-caption'))};if(n.portrait){const img=el('img');img.src=n.portrait;img.alt='';img.draggable=false;img.loading='lazy';img.onerror=fallback;box.append(img)}else fallback();return box}
 function render(){nodes.replaceChildren();seals.replaceChildren();svg.replaceChildren();nodeEls.clear();edgeEls.clear();for(const e of board.edges){const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','case-thread');svg.append(path);const seal=el('button',e.note||'添加备注','case-seal'+(e.note==='冒险团成员'?' membership':''));seal.type='button';seal.setAttribute('aria-label',a.name+'与'+b.name+'的连线');seal.title=e.note||'尚无连线备注';seal.onclick=()=>select('edge',e.id);seals.append(seal);edgeEls.set(e.id,{path,seal})}for(const [index,n] of board.nodes.entries()){const b=el('button',undefined,'case-node');b.type='button';b.dataset.id=n.id;b.dataset.kind=n.kind;b.dataset.status=n.status;b.style.setProperty('--tilt',((index%3)-1)*1.5+'deg');b.setAttribute('aria-label',n.name);if(n.kind!=='group')b.append(portrait(n));b.append(el('strong',n.name),el('small',n.role||(n.kind==='person'?'人物档案':'线索档案')));if(n.status)b.append(el('small',n.status));b.onclick=()=>{if(suppressClick){suppressClick=false;return}if(connecting){if(!source){source=n.id;geometry();hint();return}if(source===n.id){hint('请选择另一个档案');return}const existing=board.edges.find(e=>[e.from,e.to].includes(source)&&[e.from,e.to].includes(n.id));openEdge(existing||{id:crypto.randomUUID(),from:source,to:n.id,note:''});source=null;connecting=false;syncMode();return}select('node',n.id)};b.addEventListener('keydown',e=>{if(!editing||connecting||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();n.x=Math.max(100,Math.min(1700,n.x+(e.key==='ArrowRight'?20:e.key==='ArrowLeft'?-20:0)));n.y=Math.max(110,Math.min(1090,n.y+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)));geometry();save()});nodes.append(b);nodeEls.set(n.id,b)}geometry();details()}
 function select(kind,id){selection={kind,id};geometry();details()}
 function details(){const d=q('#boardDetails'),body=q('#boardDetailBody'),item=selection?.kind==='node'?board.nodes.find(n=>n.id===selection.id):board.edges.find(e=>e.id===selection?.id);d.hidden=!item;if(!item)return;q('#boardModify').hidden=q('#boardRemove').hidden=!editing;q('#boardDetailKind').textContent=selection.kind==='node'?({person:'人物档案',place:'地点档案',group:'组织档案'}[item.kind]):'连线封签';q('#boardDetailTitle').textContent=selection.kind==='node'?item.name:board.nodes.find(n=>n.id===item.from).name+' ↔ '+board.nodes.find(n=>n.id===item.to).name;body.replaceChildren();function field(title,value){body.append(el('h3',title),el('p',value||'尚未记录'))}if(selection.kind==='edge'){field('连线备注',item.note);q('#boardModify').textContent='编辑备注'}else{q('#boardModify').textContent='编辑资料';if(item.portrait){const img=el('img');img.src=item.portrait;img.alt=item.name;body.append(img)}else body.append(el('p','肖像待绘 · 可在工作台补全'));field('身份',[item.race,item.role,item.status].filter(Boolean).join(' · '));field('人物备注',item.notes);if(item.appearance)field('肖像描述',item.appearance)}if(!editing)body.append(el('p','开启编辑模式后可修改。'))}
 function syncMode(){q('#boardEdit').setAttribute('aria-pressed',String(editing));q('#boardEdit').textContent=editing?'完成编辑':'编辑模式';q('#boardNew').hidden=q('#boardConnect').hidden=!editing;q('#boardConnect').setAttribute('aria-pressed',String(connecting));world.classList.toggle('connecting',connecting);geometry();details();hint()}
 q('#boardEdit').onclick=()=>{if(!ready)return;cancelDrag();editing=!editing;connecting=false;source=null;syncMode()};q('#boardConnect').onclick=()=>{connecting=!connecting;source=null;selection=null;q('#boardDetails').hidden=true;syncMode()};q('#boardCloseDetails').onclick=()=>{selection=null;q('#boardDetails').hidden=true;geometry()};
 function openPerson(n){draft=n?core.copy(n):{id:crypto.randomUUID(),kind:'person',name:'',race:'',role:'',status:'',notes:'',appearance:'',portrait:'',x:Math.max(100,Math.min(1700,(view.clientWidth/2-tx)/zoom)),y:Math.max(110,Math.min(1090,(view.clientHeight/2-ty)/zoom))};q('#boardPersonHeading').textContent=n?'编辑档案':'新建人物';for(const [field,id] of Object.entries({name:'Name',race:'Race',role:'Role',status:'Status',notes:'Notes',appearance:'Appearance',portrait:'Portrait'}))q('#board'+id).value=draft[field];q('#boardPersonError').textContent='';q('#boardPersonDialog').showModal();q('#boardName').focus()}
 q('#boardNew').onclick=()=>openPerson();document.querySelectorAll('[data-close-person]').forEach(b=>b.onclick=()=>q('#boardPersonDialog').close());q('#boardPersonDialog').addEventListener('close',()=>draft=null);
 q('#boardPersonForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!draft)return;try{const n={...draft};for(const [field,id] of Object.entries({name:'Name',race:'Race',role:'Role',status:'Status',notes:'Notes',appearance:'Appearance',portrait:'Portrait'}))n[field]=q('#board'+id).value.trim();const next=core.copy(board),i=next.nodes.findIndex(x=>x.id===n.id);if(i<0)next.nodes.push(n);else next.nodes[i]=n;board=core.validate(next);selection={kind:'node',id:n.id};q('#boardPersonDialog').close();render();save()}catch(err){q('#boardPersonError').textContent=err.message}};
 function openEdge(e){edgeDraft=core.copy(e);q('#boardEdgeNames').textContent=board.nodes.find(n=>n.id===e.from).name+' ↔ '+board.nodes.find(n=>n.id===e.to).name;q('#boardEdgeNote').value=e.note;q('#boardEdgeDialog').showModal();q('#boardEdgeNote').focus()}
 q('#boardCancelEdge').onclick=()=>q('#boardEdgeDialog').close();q('#boardEdgeDialog').addEventListener('close',()=>edgeDraft=null);q('#boardEdgeForm').onsubmit=e=>{e.preventDefault();if(!ready||!editing||!edgeDraft)return;const next=core.copy(board),edge={...edgeDraft,note:q('#boardEdgeNote').value.trim()},i=next.edges.findIndex(x=>x.id===edge.id);if(i<0)next.edges.push(edge);else next.edges[i]=edge;try{board=core.validate(next);selection={kind:'edge',id:edge.id};q('#boardEdgeDialog').close();render();save()}catch(err){hint(err.message)}};
 q('#boardModify').onclick=()=>{if(!editing||!selection)return;if(selection.kind==='node')openPerson(board.nodes.find(n=>n.id===selection.id));else openEdge(board.edges.find(e=>e.id===selection.id))};q('#boardRemove').onclick=()=>{if(!editing||!selection)return;q('#boardDeleteText').textContent=selection.kind==='node'?'这份档案及其连线将从案件板移除。':'只移除这条连线，人物档案保留。';q('#boardDeleteDialog').showModal()};q('#boardKeep').onclick=()=>q('#boardDeleteDialog').close();q('#boardConfirmDelete').onclick=()=>{if(!editing||!selection)return;const {kind,id}=selection;board.edges=board.edges.filter(e=>kind==='edge'?e.id!==id:e.from!==id&&e.to!==id);if(kind==='node')board.nodes=board.nodes.filter(n=>n.id!==id);selection=null;q('#boardDeleteDialog').close();render();save()};
 view.addEventListener('pointerdown',e=>{if(!ready||e.button!==0||e.target.closest('.case-seal'))return;const card=e.target.closest('.case-node');if(card&&(!editing||connecting))return;suppressClick=false;const n=card?board.nodes.find(n=>n.id===card.dataset.id):null;drag={id:e.pointerId,sx:e.clientX,sy:e.clientY,tx,ty,n,oldX:n?.x,oldY:n?.y,moved:false};view.setPointerCapture(e.pointerId);if(n)card.classList.add('dragging')});
 view.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.sx,dy=e.clientY-drag.sy;if(!drag.moved&&Math.hypot(dx,dy)<5)return;drag.moved=true;if(drag.n){drag.n.x=Math.max(100,Math.min(1700,drag.oldX+dx/zoom));drag.n.y=Math.max(110,Math.min(1090,drag.oldY+dy/zoom));geometry()}else{tx=drag.tx+dx;ty=drag.ty+dy;camera()}});
 function finishDrag(e,cancel=false){if(!drag||e&&e.pointerId!==drag.id)return;const d=drag;drag=null;if(view.hasPointerCapture(d.id))view.releasePointerCapture(d.id);if(d.n){nodeEls.get(d.n.id)?.classList.remove('dragging');if(cancel){d.n.x=d.oldX;d.n.y=d.oldY;geometry()}else if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,0);save()}else if(!connecting)select('node',d.n.id)}else if(cancel){tx=d.tx;ty=d.ty;camera()}}
 function cancelDrag(){finishDrag(null,true)}view.addEventListener('pointerup',e=>finishDrag(e));view.addEventListener('pointercancel',e=>finishDrag(e,true));view.addEventListener('wheel',e=>{e.preventDefault();if(drag)return;const r=view.getBoundingClientRect();changeZoom(e.deltaY<0?1.12:1/1.12,e.clientX-r.left,e.clientY-r.top)},{passive:false});
 q('#boardPlus').onclick=()=>changeZoom(1.2);q('#boardMinus').onclick=()=>changeZoom(1/1.2);q('#boardFit').onclick=fit;view.addEventListener('keydown',e=>{if(e.target!==view||!e.key.startsWith('Arrow'))return;e.preventDefault();tx+=e.key==='ArrowRight'?-80:e.key==='ArrowLeft'?80:0;ty+=e.key==='ArrowDown'?-80:e.key==='ArrowUp'?80:0;camera()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelDrag();connecting=false;source=null;syncMode()}});
 let vw=0,vh=0;function resized(){const w=view.clientWidth,h=view.clientHeight;if(initialized){tx+=(w-vw)/2;ty+=(h-vh)/2;camera()}vw=w;vh=h}window.addEventListener('resize',()=>{cancelDrag();resized()});if(window.ResizeObserver)new ResizeObserver(resized).observe(view);
 q('#boardFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{hint('当前浏览器不支持全屏，案件板已铺满窗口。')}};document.addEventListener('fullscreenchange',()=>{const active=!!document.fullscreenElement;q('#boardFullscreen').textContent=active?'退出全屏':'全屏';q('#boardFullscreen').setAttribute('aria-pressed',String(active))});
 window.CaseboardAPI={read:()=>{const s=core.copy(board);if(drag?.n){const n=s.nodes.find(n=>n.id===drag.n.id);n.x=drag.oldX;n.y=drag.oldY}return s},apply:s=>{board=core.validate(s);if(selection&&!(selection.kind==='node'?board.nodes:board.edges).some(x=>x.id===selection.id))selection=null;render()},canApply:()=>!drag&&!connecting&&!document.querySelector('dialog[open]:not(#adventureSaveDialog)'),ready:()=>{ready=true;view.inert=false;q('#boardEdit').disabled=false;if(!initialized){initialized=true;vw=view.clientWidth;vh=view.clientHeight;fit()}hint()}};
 render();if(demo){CaseboardAPI.ready();q('[data-archive-status]').textContent='演示 · 不写入存档'}
})();
