(()=>{
 'use strict';const viewport=document.querySelector('#viewport'),q=s=>document.querySelector(s);let book=window.JOURNAL_CORE.initial(),active=null,placing=false,ready=false,focused=false,start=null;
 const requested=new URLSearchParams(location.search).get('journalPlace');
 const button=document.createElement('button');button.id='journalSaveStatus';button.textContent='读取日志…';q('footer').append(button);
 const link=document.createElement('a');link.className='map-return';link.href='./journal.html';link.textContent='冒险日志';q('header nav').prepend(link);
 const panel=document.createElement('aside');panel.id='journalPlacesPanel';panel.hidden=!requested;panel.innerHTML='<button id="closeJournalPlaces" aria-label="关闭日志地点">×</button><h2>日志地点</h2><select id="journalPlaceSelect" aria-label="选择日志地点"></select><p id="journalPlaceNote"></p><button id="positionJournalPlace">在地图指定落点</button><button id="cancelJournalPlace" hidden>取消定位</button><button id="clearJournalPlace" hidden>清除落点</button><span id="clearPlaceConfirm" hidden><p>清除这个日志地点的落点？正文和已有棋子仍保留。</p><button id="confirmClearPlace">确认清除</button><button id="keepPlace">保留</button></span><div id="journalPlaceEntries"></div>';viewport.append(panel);
 const toggle=document.createElement('button');toggle.textContent='日志地点';toggle.id='journalPlacesToggle';q('header nav').append(toggle);toggle.onclick=()=>{panel.hidden=!panel.hidden};q('#closeJournalPlaces').onclick=()=>{panel.hidden=true;stop()};
 const related=document.createElement('section');related.id='pieceJournalEntries';q('#details').append(related);let markers=[];
 function getPosition(p){const bound=p.pieceId?pieces.find(x=>String(x.id)===p.pieceId):null;return bound?{x:bound.x,y:bound.y}:p}
 function showEntries(target,placeIds){target.replaceChildren();const entries=book.entries.filter(e=>e.placeIds.some(id=>placeIds.includes(id)));if(!entries.length)return;const h=document.createElement('h3');h.textContent='关联冒险日志';target.append(h);for(const e of entries){const a=document.createElement('a');a.href='./journal.html#'+encodeURIComponent(e.id);a.textContent=e.day+' · '+e.title;target.append(a)}}
 function stop(){placing=false;start=null;q('#cancelJournalPlace').hidden=true;q('#positionJournalPlace').textContent='在地图指定落点';viewport.classList.remove('journal-positioning')}
 function focus(p){const pos=getPosition(p);if(pos.x===null)return;stopRebound();x=viewport.clientWidth/2-pos.x*scale;y=viewport.clientHeight/2-pos.y*scale;clampView();paint()}
 function selectPlace(id,center=false){active=book.places.find(p=>p.id===id)||book.places[0];q('#journalPlaceEntries').replaceChildren();q('#journalPlaceNote').textContent='';q('#clearPlaceConfirm').hidden=true;q('#clearJournalPlace').hidden=!active||active.x===null;if(!active)return;q('#journalPlaceSelect').value=active.id;q('#journalPlaceNote').textContent=active.note+(active.x===null?' 尚未在地图定位。':'');showEntries(q('#journalPlaceEntries'),[active.id]);if(center)focus(active)}
 function render(){
  for(const m of markers)m.el.remove();markers=[];q('#journalPlaceSelect').replaceChildren();for(const p of book.places){q('#journalPlaceSelect').append(new Option(p.name,p.id));if(getPosition(p).x===null||p.pieceId&&pieces.some(piece=>String(piece.id)===p.pieceId))continue;const el=document.createElement('button');el.className='journal-map-point';el.title='查看 '+p.name+' 的冒险日志';el.setAttribute('aria-label',el.title);const mark=document.createElement('img');mark.src='assets/images/map-tokens/'+({'baldurs-gate':'port','mining-town':'village','reclaimed-fort':'castle'}[p.id]||'event')+'.png';mark.alt='';mark.draggable=false;const label=document.createElement('small');label.textContent=p.name;el.append(mark,label);el.onclick=e=>{e.stopPropagation();panel.hidden=false;selectPlace(p.id)};viewport.append(el);markers.push({el,p})}
  selectPlace(active?.id||requested||book.places[0]?.id);if(!focused&&requested&&ready){focused=true;if(active)focus(active)}paintLinks();
 }
 function paintLinks(){for(const {el,p} of markers){const pos=getPosition(p);el.style.left=(x+pos.x*scale)+'px';el.style.top=(y+pos.y*scale)+'px';el.hidden=pos.x===null}const ids=selected?book.places.filter(p=>p.pieceId===String(selected.id)).map(p=>p.id):[];showEntries(related,ids)}
 const originalPaint=paint;paint=function(){originalPaint();paintLinks()};
 function commit(px,py,pieceId=null){if(!ready||!active)return;const p=book.places.find(p=>p.id===active.id);p.x=px;p.y=py;p.pieceId=pieceId;stop();document.dispatchEvent(new CustomEvent('journal:change',{detail:structuredClone(book)}));render()}
 q('#clearJournalPlace').onclick=()=>{q('#clearPlaceConfirm').hidden=false};q('#keepPlace').onclick=()=>{q('#clearPlaceConfirm').hidden=true};q('#confirmClearPlace').onclick=()=>{if(ready&&active)commit(null,null)};
 let receivedMap=false;document.addEventListener('map:restored',()=>{if(!receivedMap){focused=false;receivedMap=true}render()});
 q('#journalPlaceSelect').onchange=e=>{stop();selectPlace(e.target.value,true)};
 q('#positionJournalPlace').onclick=()=>{if(!ready)return;cancel();setMoveMode(false);placing=true;q('#cancelJournalPlace').hidden=false;q('#positionJournalPlace').textContent='点击地图，或选择已有棋子';viewport.classList.add('journal-positioning')};q('#cancelJournalPlace').onclick=stop;
 viewport.addEventListener('pointerdown',e=>{if(!placing||e.button!==0||e.target.closest('aside'))return;const el=e.target.closest('.piece');if(el){e.stopImmediatePropagation();e.preventDefault();const p=pieces.find(p=>p.el===el);if(p)commit(p.x,p.y,String(p.id));return}if(e.target.closest('button'))return;start={x:e.clientX,y:e.clientY};},true);
 viewport.addEventListener('pointerup',e=>{if(!placing||!start)return;const origin=start;start=null;if(Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>6)return;const r=viewport.getBoundingClientRect(),px=(e.clientX-r.left-x)/scale,py=(e.clientY-r.top-y)/scale;if(px<0||px>4763||py<0||py>3185)return;e.stopImmediatePropagation();drag=null;if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);commit(px,py)},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape')stop()});viewport.addEventListener('pointercancel',()=>{start=null});
 document.addEventListener('map:save',()=>{if(!ready)return;let changed=false;for(const place of book.places){if(!place.pieceId)continue;const p=pieces.find(p=>String(p.id)===place.pieceId);if(p&&(place.x!==p.x||place.y!==p.y)){place.x=p.x;place.y=p.y;changed=true}else if(!p){place.pieceId=null;changed=true}}if(changed)document.dispatchEvent(new CustomEvent('journal:change',{detail:structuredClone(book)}));render()});
 window.JournalAPI={read:()=>structuredClone(book),apply:s=>{book=window.JOURNAL_CORE.validate(s);render()},canApply:()=>!placing&&!pieceDrag&&!drag,ready:()=>{ready=true;render()},block:()=>{ready=false;q('#positionJournalPlace').disabled=true}};
 render();
})();
