(()=>{
 'use strict';const q=s=>document.querySelector(s),core=CASEBOARD_CORE,links=BOARD_MAP_LINKS,demo=new URLSearchParams(location.search).has('showcase');
 let board=core.initial(),ready=false,targetId=null,renderKey='',focusId=new URLSearchParams(location.search).get('piece');
 const section=document.createElement('section');section.className='piece-people';section.id='piecePeople';q('#details').append(section);
 const dialog=document.createElement('dialog');dialog.id='mapPersonDialog';dialog.className='map-person-dialog';dialog.setAttribute('aria-labelledby','mapPersonHeading');
 dialog.innerHTML='<form id="mapPersonForm"><h2 id="mapPersonHeading">关联人物</h2><p id="mapPersonLocation"></p><label>人物来源<select id="mapPersonSource"><option value="existing">已有档案</option><option value="new">新建人物</option></select></label><label id="mapPersonExistingField">选择人物<select id="mapPersonExisting"></select></label><div id="mapPersonNewFields" hidden><label>名称<input id="mapPersonName" maxlength="100"></label><label>种族<input id="mapPersonRace" maxlength="100"></label><label>职业<input id="mapPersonRole" maxlength="100"></label><label>等级<select id="mapPersonLevel"><option value="?">？（未知）</option>'+Array.from({length:20},(_,i)=>'<option value="'+(i+1)+'">'+(i+1)+'</option>').join('')+'</select></label><label>特殊状态<input id="mapPersonStatus" maxlength="100" placeholder="已故 / 未知 / 失踪"></label><label>备注<textarea id="mapPersonNotes" maxlength="4000" rows="3"></textarea></label><label>外貌描述<textarea id="mapPersonAppearance" maxlength="2000" rows="2"></textarea></label></div><p id="mapPersonMatch"></p><p id="mapPersonError" role="alert"></p><menu><button type="button" id="mapPersonCancel">取消</button><button type="submit">保存关联</button></menu></form>';
 document.body.append(dialog);
 function sourceChanged(){const fresh=q('#mapPersonSource').value==='new';q('#mapPersonHeading').textContent=fresh?'在此新建人物':'关联已有人物';q('#mapPersonForm [type=submit]').textContent=fresh?'保存人物':'保存关联';q('#mapPersonNewFields').hidden=!fresh;q('#mapPersonExistingField').hidden=fresh;q('#mapPersonName').required=fresh;q('#mapPersonMatch').textContent=''}
 q('#mapPersonSource').onchange=sourceChanged;q('#mapPersonCancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{targetId=null});
 q('#mapPersonName').oninput=()=>{const matches=links.sameName(board.nodes,q('#mapPersonName').value);q('#mapPersonMatch').textContent=matches.length?'已有同名档案，请切换“已有档案”选择，避免重复创建。':''};
 function open(source){if(!ready||!selected)return;targetId=String(selected.id);q('#mapPersonForm').reset();q('#mapPersonSource').value=source;q('#mapPersonLocation').textContent='关联地点：'+selected.name;q('#mapPersonError').textContent='';const picker=q('#mapPersonExisting');picker.replaceChildren(new Option('选择已有的人物…',''));for(const n of board.nodes.filter(n=>n.kind==='person')){const old=pieces.find(p=>String(p.id)===n.mapPieceId);picker.append(new Option(n.name+(old?' · '+old.name:''),n.id))}sourceChanged();dialog.showModal()}
 function save(next){board=core.validate(next);if(!demo)document.dispatchEvent(new CustomEvent('board:change',{detail:core.copy(board)}));renderKey='';render()}
 q('#mapPersonForm').onsubmit=e=>{e.preventDefault();if(!ready||!targetId)return;try{const place=pieces.find(p=>String(p.id)===targetId);if(!place)throw Error('这个地点已移除，请重新选择');const next=core.copy(board);let n;
  if(q('#mapPersonSource').value==='existing'){n=next.nodes.find(n=>n.id===q('#mapPersonExisting').value&&n.kind==='person');if(!n)throw Error('请选择一个人物')}
  else{const name=q('#mapPersonName').value.trim();if(!name)throw Error('请填写名称');if(links.sameName(next.nodes,name).length)throw Error('已有同名人物，请切换“已有档案”选择');const anchor=next.nodes.find(n=>n.mapPieceId===targetId&&n.kind==='place');const nearby=next.nodes.filter(n=>n.mapPieceId===targetId).length;
   n={id:crypto.randomUUID(),kind:'person',name,race:q('#mapPersonRace').value.trim(),role:q('#mapPersonRole').value.trim(),level:q('#mapPersonLevel').value==='?'?null:Number(q('#mapPersonLevel').value),status:q('#mapPersonStatus').value.trim(),notes:q('#mapPersonNotes').value.trim(),appearance:q('#mapPersonAppearance').value.trim(),portrait:'',x:(anchor?.x||600)+(nearby%4)*200,y:(anchor?.y||400)+280+Math.floor(nearby/4)*280};next.nodes.push(n)}
  n.mapPieceId=targetId;save(next);dialog.close();render();
 }catch(error){q('#mapPersonError').textContent=error.message}};
 function render(){
  const people=selected?board.nodes.filter(n=>n.kind==='person'&&n.mapPieceId===String(selected.id)):[],key=JSON.stringify([selected?.id,ready,people]);if(key===renderKey)return;renderKey=key;section.replaceChildren();const h=document.createElement('h3');h.textContent='地点人物'+(people.length?' · '+people.length:'');section.append(h);
  for(const n of people){const a=document.createElement('a');a.className='piece-person';a.href='./caseboard.html?person='+encodeURIComponent(n.id);const image=document.createElement(n.portrait?'img':'span');if(n.portrait){image.src=n.portrait;image.alt='';image.draggable=false}else{image.className='portrait-placeholder';image.textContent=n.name[0]}const words=document.createElement('span'),name=document.createElement('strong'),info=document.createElement('small');name.textContent=n.name;info.textContent=links.preview(n);words.append(name,info);a.append(image,words);section.append(a)}
  if(!people.length){const empty=document.createElement('p');empty.textContent=ready?'尚未关联人物。':'正在读取人物档案…';section.append(empty)}const actions=document.createElement('div');actions.className='people-actions';for(const [label,source] of [['关联已有人物','existing'],['在此新建人物','new']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=!ready;b.onclick=()=>open(source);actions.append(b)}section.append(actions);
 }
 function focus(){if(!focusId||q('#viewport').inert)return;const p=pieces.find(p=>String(p.id)===focusId);if(!p)return;focusId=null;home();x=viewport.clientWidth/2-p.x*scale;y=viewport.clientHeight/2-p.y*scale;clampView();select(p)}
 const originalPaint=paint;paint=function(){originalPaint();render()};
 document.addEventListener('map:restored',()=>{links.set(MapTable.read());renderKey='';render();focus()});document.addEventListener('map:save',()=>{links.set(MapTable.read());renderKey='';render()});
 const originalReady=()=>{ready=true;renderKey='';render();focus()};
 window.CaseboardAPI={read:()=>core.copy(board),apply:s=>{board=core.validate(s);renderKey='';render()},canApply:()=>!dialog.open,ready:originalReady};
 // Hold map edits too while the creation form is open, so its selected place stays stable.
 const mapCanApply=MapTable.canApply;MapTable.canApply=()=>mapCanApply()&&!dialog.open;
 const mapApply=MapTable.apply;MapTable.apply=s=>{mapApply(s);queueMicrotask(focus)};
 render();if(demo){ready=true;links.set(MapTable.read());render()}
})();
