const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {PartStore,validateArchive,equal}=require('../archive-core');
const copy=v=>structuredClone(v),valid=s=>{if(!s||typeof s.value!=='string')throw Error('bad');return copy(s)};
function storage(){const m=new Map();return {m,getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)}}
function remote(){return {row:{revision:3,updatedAt:'2026-09-15T00:00:00Z',snapshot:{value:'cloud'}},calls:0,offline:false,async load(){if(this.offline)throw Error('offline');return copy(this.row)},async save(r,s){this.calls++;if(r!==this.row.revision)return {status:'conflict',row:copy(this.row)};this.row={revision:r+1,updated_at:'2026-09-15T00:00:01Z',snapshot:copy(s)};return {status:'saved',row:copy(this.row)}}}}
function device(server,local=storage()){let view={value:'old-default'};const s=new PartStore({name:'map',storage:local,validate:valid,read:()=>view,apply:v=>view=v,load:()=>server.load(),save:(r,v)=>server.save(r,v)});return {s,local,read:()=>view,edit(value){view={value};s.capture(view)}}}
test('fresh device uses current owner cloud without uploading defaults; edits and reload persist',async()=>{const r=remote(),a=device(r);a.s.authorized=true;await a.s.sync();assert.equal(a.read().value,'cloud');assert.equal(r.calls,0);a.edit('new');await a.s.sync();assert.equal(r.row.snapshot.value,'new');const b=device(r);await b.s.sync();assert.equal(b.read().value,'new');assert([...a.local.m.keys()].some(k=>k.startsWith('dndcard-archive-backup:')))});
test('offline dirty data survives reload, old Git fallback cannot overwrite it',async()=>{const r=remote(),a=device(r);await a.s.sync();a.edit('offline');r.offline=true;const b=device(r,a.local);await b.s.sync();assert.equal(b.read().value,'offline');assert(b.s.entry.dirty);r.offline=false;r.row.revision=2;await b.s.sync();assert.equal(b.read().value,'offline');assert.equal(b.s.status,'error');r.row.revision=3;b.s.authorized=true;await b.s.sync();assert.equal(r.row.snapshot.value,'offline')});
test('two devices conflict preserves both versions; explicit resolution rechecks the server',async()=>{const r=remote(),a=device(r),b=device(r);a.s.authorized=b.s.authorized=true;await a.s.sync();await b.s.sync();a.edit('A');b.edit('B');await a.s.sync();await b.s.sync();assert.equal(b.s.status,'conflict');assert.equal(r.row.snapshot.value,'A');r.row.revision++;await b.s.resolve(true);assert.equal(b.s.status,'conflict');await b.s.resolve(false);assert.equal(b.read().value,'A');assert([...b.local.m.keys()].filter(k=>k.startsWith('dndcard-archive-backup:')).length>=3)});
test('edit during upload remains pending, next save sends newest data',async()=>{const r=remote(),a=device(r);a.s.authorized=true;await a.s.sync();a.edit('first');let release;const original=r.save.bind(r);r.save=async(...args)=>{await new Promise(resolve=>release=resolve);return original(...args)};const pending=a.s.sync();while(!release)await new Promise(r=>setTimeout(r,0));a.edit('second');release();await pending;assert(a.s.entry.dirty);assert.equal(r.row.snapshot.value,'first');r.save=original;await a.s.sync();assert.equal(r.row.snapshot.value,'second')});
test('concurrent tab local writes cannot silently overwrite shared cache',async()=>{const r=remote(),local=storage(),a=device(r,local);await a.s.sync();const b=device(r,local);await b.s.sync();a.edit('A');assert.throws(()=>b.edit('B'),/另一页面/);assert.equal(JSON.parse(local.getItem(a.s.key)).snapshot.value,'A');assert.equal(b.s.status,'storage-error')});
test('anonymous edits stay on device until owner authorization',async()=>{const r=remote(),a=device(r);await a.s.sync();a.edit('guest');await a.s.sync();assert.equal(r.calls,0);assert.equal(a.s.status,'local');a.s.authorized=true;await a.s.sync();assert.equal(r.calls,1)});
test('storage quota failure blocks migration instead of claiming saved',async()=>{const r=remote(),local=storage();local.setItem=()=>{throw Error('quota')};const a=device(r,local);await a.s.sync();assert.equal(a.s.status,'storage-error');assert.equal(a.s.ready,false);assert.equal(a.read().value,'old-default');assert.equal(r.calls,0)});

function archive(){const window={};vm.runInNewContext(fs.readFileSync('journal-seed.js','utf8'),{window});return {format:'dndcard-adventure',version:1,revision:5,updatedAt:'2026-09-15T00:00:00Z',parts:{character:{revision:3,updatedAt:'2026-09-15T00:00:00Z',snapshot:JSON.parse(fs.readFileSync('data/submissions/dndcard-full-2026-09-14T14-52-46-628Z-77c21d46.json'))},map:{revision:19,updatedAt:'2026-09-15T00:00:00Z',snapshot:require('../map-save-core').initial()},journal:{revision:1,updatedAt:'2026-09-15T00:00:00Z',snapshot:window.JOURNAL_SEED}},assets:{repository:'Sherlock3rd/DNDcard'}}}
test('complete archives require all sections; JSON key order does not matter',()=>{const a=archive();validateArchive(a);const b=copy(a);delete b.parts.map;assert.throws(()=>validateArchive(b));assert(equal({a:1,b:2},{b:2,a:1}))});
test('Git worker commits complete snapshot, retries CAS, verifies exact commit, skips duplicates',async()=>{const {sync}=require('./sync-adventure-git'),a=archive();let file=null,puts=0;const response=(status,data)=>({ok:status<300,status,json:async()=>data});const f=async(url,o)=>{if(url.includes('supabase.co'))return response(200,[{snapshot:a}]);if(o.method==='PUT'){puts++;if(puts===1)return response(409,{});file=JSON.parse(o.body).content;return response(200,{commit:{sha:'commit-5'}})}return file?response(200,{sha:'blob',content:file}):response(404,{})};const result=await sync({fetcher:f,token:'test-only'});assert.equal(result.status,'saved');assert.equal(puts,2);assert.equal((await sync({fetcher:f,token:'test-only'})).status,'unchanged');a.revision=4;await assert.rejects(sync({fetcher:f,token:'test-only'}),/newer Git/)});
test('Git worker never reports success after failed verification',async()=>{const {sync}=require('./sync-adventure-git'),a=archive();let saved=false;const f=async(url,o)=>({ok:true,status:200,json:async()=>url.includes('supabase.co')?[{snapshot:a}]:o.method==='PUT'?(saved=true,{commit:{sha:'abc'}}):saved?{content:Buffer.from('{}').toString('base64')}:{sha:'old',content:Buffer.from(JSON.stringify({...a,revision:4})).toString('base64')}});await assert.rejects(sync({fetcher:f,token:'test'}),/read-back mismatch/)});

test('journal image navigation ignores late responses, preloads adjacent optimized images',async()=>{const {JSDOM}=require('jsdom'),dom=new JSDOM('<figure><button id="imageStatus"></button><img id="chapterImage"></figure>',{runScripts:'outside-only'}),w=dom.window,images=[];w.Image=class{constructor(){images.push(this)}set src(v){this.url=v}decode(){return Promise.resolve()}};vm.runInContext(fs.readFileSync('journal-images.js','utf8'),dom.getInternalVMContext());w.JOURNAL_IMAGES.show('assets/images/journal/01-bequest.png','one');w.JOURNAL_IMAGES.show('assets/images/journal/02-departure.png','two');await images[0].onload();await new Promise(r=>setImmediate(r));assert.equal(w.document.querySelector('img').getAttribute('src'),null);await images[1].onload();await new Promise(r=>setImmediate(r));assert(w.document.querySelector('img').src.endsWith('02-departure.webp'));assert.equal(w.document.querySelector('#imageStatus').hidden,true);w.JOURNAL_IMAGES.preload([{image:'assets/images/journal/01-bequest.png'},{image:'assets/images/journal/02-departure.png'},{image:'assets/images/journal/03-recruitment.png'}],1);assert(images.some(i=>i.url.endsWith('03-recruitment.webp')));dom.window.close()});
module.exports={archive};
