const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),core=require('../caseboard-core');
function seed(){const w={};vm.runInNewContext(fs.readFileSync('caseboard-seed.js','utf8'),{window:w});return core.validate(w.CASEBOARD_SEED)}
test('caseboard preserves existing cast, validates references and allows a blank portrait',()=>{const s=seed();assert.equal(s.nodes.length,13);assert.equal(s.edges.length,14);for(const n of s.nodes)if(n.portrait)assert(fs.existsSync(n.portrait));s.nodes.push({id:'new',kind:'person',name:'新证人',race:'',role:'',status:'',notes:'',appearance:'',portrait:'',x:500,y:500});core.validate(s);s.edges.push({id:'new-link',from:'new',to:'party',note:'目击者'});core.validate(s);s.nodes.pop();assert.throws(()=>core.validate(s));});
test('caseboard rejects duplicate connections, unsafe portraits, bad coordinates and oversized notes',()=>{for(const mutate of [s=>s.edges.push({...s.edges[0],id:'duplicate',from:s.edges[0].to,to:s.edges[0].from}),s=>s.nodes[0].portrait='javascript:alert(1)',s=>s.nodes[0].portrait='assets/images/../secret',s=>s.nodes[0].x=NaN,s=>s.nodes[0].notes='x'.repeat(4001)]){const s=seed();mutate(s);assert.throws(()=>core.validate(s))}});

test('wards validate bounds, preserve empty groups and upgrade legacy snapshots without touching cards',()=>{
 const s=seed();assert.equal(s.zones.length,2);const legacy=JSON.parse(JSON.stringify(s));delete legacy.zones;assert.deepEqual(core.validate(legacy).zones,[]);assert.deepEqual(core.validate(legacy).nodes,JSON.parse(JSON.stringify(s.nodes)));s.zones=[];assert.deepEqual(core.validate(s).zones,[]);
 for(const mutate of [s=>s.zones=null,s=>s.zones.push({...s.zones[0]}),s=>s.zones[0].width=NaN,s=>s.zones[0].x=-1,s=>s.zones[0].height=199,s=>s.zones[0].width=1800,s=>s.zones[0].tone='red',s=>s.zones[0].name='']){const s=seed();mutate(s);assert.throws(()=>core.validate(s))}
});
