"""Deterministic extraction of the user-approved room; no generated/repainted pixels.

Run with Pillow + numpy. --check verifies committed assets without rewriting them.
All layers retain the source canvas and are disjoint; their sum is the source.
"""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / 'assets/images/room'
spec = json.loads((ASSETS / 'layers.json').read_text(encoding='utf-8'))
source = Image.open(ASSETS / spec['source']).convert('RGBA')
assert source.size == (spec['width'], spec['height'])
pixels = np.array(source)
owner = np.zeros((source.height, source.width), dtype=np.uint8)
for index, layer in enumerate(spec['layers'], 1):
    mask = Image.new('L', source.size)
    ImageDraw.Draw(mask).polygon([tuple(p) for p in layer['polygon']], fill=255)
    owner[np.array(mask) != 0] = index

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
files = ['background.png'] + [layer['file'] for layer in spec['layers']]
composite = np.zeros_like(pixels, dtype=np.uint16)
counts = {}
for index, filename in enumerate(files):
    expected = np.zeros_like(pixels)
    expected[owner == index] = pixels[owner == index]
    if not args.check:
        Image.fromarray(expected).save(ASSETS / filename, optimize=True)
    actual = np.array(Image.open(ASSETS / filename).convert('RGBA'))
    assert np.array_equal(actual, expected), f'{filename}: layer differs from source extraction'
    composite += actual
    counts[filename] = int(np.count_nonzero(actual[:, :, 3]))
assert np.array_equal(composite, pixels), 'Reconstruction must match the source in all RGBA channels'

report = {
    'source_sha256': hashlib.sha256((ASSETS / spec['source']).read_bytes()).hexdigest(),
    'size': list(source.size), 'compared_pixels': source.width * source.height,
    'different_pixels': int(np.count_nonzero(np.any(composite != pixels, axis=2))),
    'maximum_channel_error': int(np.abs(composite.astype(int) - pixels.astype(int)).max()),
    'opaque_pixels_by_layer': counts,
    'method': 'disjoint original-pixel extraction; no repaint, rescale, lighting or shadow changes'
}
if not args.check:
    (ASSETS / 'layout.js').write_text('/* Generated by scripts/extract-room-layers.py. */\nwindow.ROOM_LAYER_SPEC = ' + json.dumps(spec, separators=(',', ':')) + ';\n', encoding='utf-8')
    (ASSETS / 'verification.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    proof = ROOT / 'tmp/room-proof'
    proof.mkdir(parents=True, exist_ok=True)
    Image.fromarray(composite.astype(np.uint8)).save(proof / 'reconstructed.png')
    annotated = source.copy()
    draw = ImageDraw.Draw(annotated)
    for layer, color in zip(spec['layers'], ['#f1bb6b', '#77c8ff', '#6eddbe', '#ef88cc', '#ffff80']):
        points = [tuple(p) for p in layer['polygon']]
        draw.line(points + points[:1], fill=color, width=3)
        draw.text(tuple(layer['anchor']), layer['id'], fill=color, stroke_width=2, stroke_fill='black')
    annotated.save(proof / 'boundaries.png')
print(json.dumps(report, indent=2))
